### ISSUE TITLE
Error: Non-Error exception captured with keys: adaptyCode, code, localizedDescription

### ISSUE THREAD

**Issue by huseyintamer** [adaptyteam/AdaptySDK-React-Native#34] opened 2022-12-09 16:51 UTC
Hello, Some users get this error 
```
Error: Non-Error exception captured with keys: adaptyCode, code, localizedDescription
  at tracking.enable$argument_0.onUnhandled(node_modules/@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers.js:77:57)
  at onUnhandled(node_modules/promise/setimmediate/rejection-tracking.js:73:25)
  at apply(native)
  at setTimeout(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:214:35)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:114:15)
  at callTimers(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:357:30)
  at apply(native)
  at __callFunction(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:423:32)
  at __guard$argument_0(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:43)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:366:7)
  at callFunctionReturnFlushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:18)
```
Error detail in Sentry: https://sentry.io/share/issue/4031318580f440e4960e0687e23d3350/

Platform: Android

My dependecies
```
"react-native": "0.70.0",
"react": "18.1.0",
"react-native-adapty": "^1.3.13"
```

_I'm look forward to your help, Thanks._

**Comment by divanc** [comment] 2022-12-12 15:16
Hey! Looking into this...

**Comment by divanc** [comment] 2022-12-12 16:19
To the best of my knowledge, this error is resolved in v1.4.1 and duplicates the following issue:
* https://github.com/adaptyteam/AdaptySDK-React-Native/issues/31

This Sentry message seems to mean that `AdaptyError` does not inherit `Error` class, which was resolved in v1.4.0

**Comment by divanc** [comment] 2022-12-12 16:20
Can you try to update and confirm this log does not accumulate anymore?

**Comment by divanc** [comment] 2022-12-15 11:09
I will close this issue due to inactivity as I believe the problem is fixed. Please re-open if you think otherwise

**Closed by divanc** 2022-12-15 11:09 UTC

**Comment by huseyintamer** [comment] 2022-12-23 20:09
Confirmed Thanks  🙌🏻 @divanc
