### ISSUE TITLE
[Error: #2003 (badRequest): Server error]

### ISSUE THREAD

**Issue by snake302** [adaptyteam/AdaptySDK-React-Native#45] opened 2023-02-07 18:45 UTC
Hello,

We are encountering an issue with Adapty 2.2.1 SDK after a successful subscription purchase in the sandbox. The purchase prompt appears and displays the message "you are all set," but we receive the following error:

[Error: #2003 (badRequest): Server error]"

Shared Secret is valid & updated. Could you please check issue on your side?

**Comment by snake302** [comment] 2023-02-07 18:56
After app relaunch the subscription is active, but after purchase our paywall is not closing due error "2003"

**Comment by divanc** [comment] 2023-02-07 20:44
Hey @snake302! We are looking into it... 
It seem to only affect sandbox purchases. Still top priority

**Comment by snake302** [comment] 2023-02-07 21:01
> Hey @snake302! We are looking into it... 
> 
> It seem to only affect sandbox purchases. Still top priority

Yeah, thanks, we can't get App Store Review approve because they unable to make purchases in the Sandbox

**Comment by kpotehin** [comment] 2023-02-07 21:05
We understand it's critical for you to be able to test purchases in Sandbox. Unfortunately, we can't do anything now, because it's related to Apple's servers. We monitor the situation and update you once it will be resolved by Apple.
Production purchases work as usual, so no worries here.

**Comment by nomanoff** [comment] 2023-02-08 10:22
Hello, I am facing the same issue. We have recently integrated adapty in RN `"react-native-adapty": "^2.3.0"` and have been testing it with the sandbox. When I try to make purchase in the sandbox it shows this same error:

```
Error: #2003 (badRequest): Server error
    at new AdaptyError (error.js:18)
    at Function.AdaptyError.tryWrap (error.js:42)
    at Adapty.<anonymous> (adapty.js:483)
    at step (tslib.js:141)
    at Object.throw (tslib.js:122)
    at rejected (tslib.js:113)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:241
    at _callTimer (JSTimers.js:112)
```

Any suggestions? Thanks

**Comment by snake302** [comment] 2023-02-08 10:24
@nomanoff just wait, it’s Apple issue: https://developer.apple.com/system-status/

**Comment by divanc** [comment] 2023-02-09 16:52
We all survived through this! 
It seems, that everything is working as intended for us. I'm going to close this issue for now

**Closed by divanc** 2023-02-09 16:52 UTC
