### ISSUE TITLE
Calling adapty.activate in a simulator triggers the login request

### ISSUE THREAD

**Issue by amberv0** [adaptyteam/AdaptySDK-React-Native#60] opened 2023-03-21 19:15 UTC
### Description

Hey!
I just updated from v1 to v2.4.2 and I see the login screen pop up as soon as I call `adapty.activate(config.ADAPTY_PUBLIC_KEY)`. 

As in a simulator I would never be logged in, it's very annoying. Not sure about real users, but it's worrying. Never had this problem with v1.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/11645756/226716907-e8012101-6051-485a-a309-2f3734442e2e.png">

### Version

v2.4.2

### What platforms are you seeing the problem on?

iOS

### System info

```yml
IDEs:
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
 
npmPackages:
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3
```

**Comment by divanc** [comment] 2023-03-21 19:28
Hey, @amberv0! SDK v2 works a lot way differently under the hood. To keep user info fresh it scans his/hers receipts on activation, meaning checking whether user has purchased a product from within the AppStore or cancelled his active subscription. 

This check requires SDK to authorize request to App Store APIs, thus this authorization modal. 

While we do not plan on changing this logic in v2, we have noticed how irritating the appearing of this modal in simulator is. There soon would be an update that would provide you a had for to disable this check for emulators

Thank you for pointing out this problem 💪

**Comment by amberv0** [comment] 2023-03-21 19:34
Hey @divanc! Thanks for the very fast response!

Good to know this is going to be handled soon :) 

I still think this is a problem though, since not having an appleId is a valid scenario (though maybe rare). Isn't there a way for you to check whether there is a logged in user on a device, and if not, well, there is definitely no user info to refresh?

**Comment by divanc** [comment] 2023-03-22 03:59
I'm not sure, that there could be no App Store user if that is what you mean.
In order to download an app you need an account, and that very same account would be used for this app regardless, whether you log out or not.

While debugging on a simulator, Apple chooses to drop your session every time (in case you want to check different accounts), that is the only way, I believe, to be accountless 
@amberv0

**Comment by amberv0** [comment] 2023-03-22 11:51
True, I think you are right. While it's possible to use iphone without apple id, I think it's indeed impossible to install an app without logging in.

**Comment by divanc** [comment] 2023-03-26 14:41
I'll keep this issue open and inform, when native team will be ready to release this thing. Still, marked as in progress...

**Comment by beweinreich** [comment] 2023-04-12 20:25
+1 this is very frustrating while developing locally. Every time the app reloads, I need to dismiss this popup.

**Comment by dragonfire1119** [comment] 2023-04-29 17:13
Just upgraded, and now it says a person must sign in even though they are already signed in? This is done on an iPad.

**Comment by divanc** [comment] 2023-05-01 10:17
@dragonfire1119
On a real device? You can add your sandbox account in App Store settings. This way it shouldn't ask you every time. 
On a simulator it is a different story...

For everyone, I'm currently holding rounds of discussions with native developers. For now we haven't decided how we can approach this problem without raising some occasional unexpected behavior.

I'll let you guys know when we decide something ASAP, pinging them today

**Comment by dragonfire1119** [comment] 2023-05-04 01:37
@divanc 
Thank you for responding. Confirming that this is a user. They receive a prompt to sign in even though they are already signed in. This issue seems to be occurring only on an iPad, not an iPhone, but I am investigating further. I am unable to update at the moment as it may cause inconvenience to non-testers. What's peculiar about this issue is that it is not consistently replicable on a physical device. The previous version of this library did not have this problem.

**Comment by divanc** [comment] 2023-08-15 10:12
In v2.6.0 (with breaking changes) I've added `__debugDeferActivation` as a workaround for this problem. In the [new docs](https://docs.adapty.io/docs/react-native-configuring#delaying-sdk-activation), I've also written why it is currently the picked solution.

We were unable to arrange any viable solution on a native side. Authentication flow is triggered by Apple and we cannot control, when it is shown or what data is inside it...

Considering real-device auth, it should also not be due to any Adapty SDK functionality. Apple might choose to prompt user if he has authenticated with different account, than what he/she had used when downloading app. We spent a lot of time discussing this and testing with native team...

I'll close this issue for now, please re-open if you believe, there is a better way to resolve this issue

**Closed by divanc** 2023-08-15 10:12 UTC
Labels: enhancement
